### ISSUE TITLE
2.10.0 increased baseline from Java 1.6 to 11

### ISSUE THREAD

**Issue by marcphilipp** [sonofab1rd/univocity-parsers#19]
Thus, libraries such as JUnit 5 which use Java 8 as their baseline can't update. Was that change intentional or only made in 3557db77b478d3913e4c690fe501c008739bcb94 because your local JDK didn't support compiling for Java 1.6?

**Comment by sonofab1rd** [comment]
Sorry! That's an oversight on my part. I can change back to 6 or 8.

**Comment by marcphilipp** [comment]
That would be great!

**Comment by sonofab1rd** [comment]
@marcphilipp 2.10.1 is released! This version is using Java 1.6.

**Comment by marcphilipp** [comment]
Thanks! I just [updated](https://github.com/junit-team/junit5/commit/12e6bae6f0c48cf24ec15f484c40f25db28d4275) without any issues. :tada:
